import { FontFamily } from "@/constants/theme";
import { StyleSheet } from "react-native";

export const createSubscriptionStyles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#050511",
  },
  header: {
    paddingHorizontal: 20,
    height: 60,
    justifyContent: "center",
  },
  scrollContent: {
    paddingHorizontal: 20,
    paddingBottom: 20,
  },
  heroSection: {
    marginTop: 10,
    gap: 20,
    marginBottom: 40,
  },
  iconWrapper: {
    width: 80,
    height: 80,
    borderRadius: 20,
    backgroundColor: "#101019",
    borderWidth: 1,
    borderColor: "#1A1A2E",
    justifyContent: "center",
    alignItems: "center",
    marginBottom: 16,
    overflow: "hidden",
  },
  logo: {
    width: 50,
    height: 50,
    resizeMode: "contain",
  },
  placeholderIcon: {
    width: 50,
    height: 50,
    borderRadius: 10,
    backgroundColor: "#4649E5",
    justifyContent: "center",
    alignItems: "center",
  },
  placeholderText: {
    color: "#fff",
    fontSize: 24,
    fontFamily: FontFamily.bold,
  },
  subscriptionName: {
    fontSize: 28,
    fontFamily: FontFamily.bold,
    color: "#fff",
  },
  form: {
    gap: 20,
  },
  groupLabel: {
    fontSize: 12,
    fontFamily: FontFamily.medium,
    color: "#4D4D61",
    marginLeft: 16,
    marginTop: 12,
    marginBottom: 8,
    textTransform: "uppercase",
    letterSpacing: 1,
  },
  fieldRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    paddingVertical: 16,
    paddingHorizontal: 18,
    backgroundColor: "#101019",
    borderRadius: 12,
  },
  fieldLabel: {
    fontSize: 16,
    fontFamily: FontFamily.regular,
    color: "#E4E4ED",
  },
  fieldValue: {
    fontSize: 16,
    fontFamily: FontFamily.medium,
    color: "#fff",
  },
  pickerTrigger: {
    flexDirection: "row",
    alignItems: "center",
  },
  priceInputContainer: {
    flexDirection: "row",
    alignItems: "center",
  },
  priceInput: {
    fontSize: 16,
    fontFamily: FontFamily.medium,
    color: "#fff",
    textAlign: "right",
    minWidth: 60,
  },
  currencyLabel: {
    fontSize: 12,
    fontFamily: FontFamily.regular,
    color: "#4D4D61",
    marginLeft: 4,
  },
  textInput: {
    fontSize: 16,
    fontFamily: FontFamily.medium,
    color: "#fff",
    flex: 1,
    marginLeft: 20,
  },
  footer: {
    paddingHorizontal: 20,
    backgroundColor: "#050511",
    paddingTop: 10,
  },
  addButton: {
    backgroundColor: "#4649E5",
    height: 56,
    borderRadius: 14,
    justifyContent: "center",
    alignItems: "center",
    shadowColor: "#4649E5",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 8,
    elevation: 5,
  },
  addButtonText: {
    fontSize: 18,
    fontFamily: FontFamily.bold,
    color: "#fff",
  },
  modalOverlay: {
    flex: 1,
    backgroundColor: "rgba(0,0,0,0.6)",
    justifyContent: "center",
    alignItems: "center",
    padding: 40,
  },
  modalContent: {
    backgroundColor: "#0A0A1A",
    borderRadius: 20,
    width: "100%",
    padding: 10,
    borderWidth: 1,
    borderColor: "#1A1A2E",
  },
  modalOption: {
    padding: 16,
    alignItems: "center",
  },
  modalOptionText: {
    fontSize: 18,
    fontFamily: FontFamily.medium,
    color: "#fff",
  },
});

export const subscriptionListStyles = StyleSheet.create({
  container: {
    flex: 1,
    paddingHorizontal: 20,
    backgroundColor: "#050511",
  },
  header: {
    flexDirection: "row",
    alignItems: "center",
    marginTop: 10,
    marginBottom: 20,
  },
  backButton: {
    marginRight: 15,
  },
  title: {
    fontSize: 24,
    fontFamily: FontFamily.bold,
    color: "#fff",
  },
  searchContainer: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "#101019",
    borderRadius: 12,
    paddingHorizontal: 15,
    height: 48,
    marginBottom: 20,
  },
  searchIcon: {
    marginRight: 10,
  },
  searchInput: {
    flex: 1,
    color: "#fff",
    fontSize: 16,
    fontFamily: FontFamily.regular,
  },
  customSubscription: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    backgroundColor: "#101019",
    borderWidth: 1,
    borderColor: "#1A1A2E",
    borderRadius: 12,
    padding: 16,
    marginBottom: 20,
  },
  customText: {
    fontSize: 16,
    fontFamily: FontFamily.medium,
    color: "#fff",
  },
  listContent: {
    paddingBottom: 20,
  },
  subscriptionItem: {
    flexDirection: "row",
    alignItems: "center",
    borderWidth: 1,
    borderColor: "#1A1A2E",
    borderRadius: 12,
    padding: 12,
    marginBottom: 12,
  },
  iconContainer: {
    justifyContent: "center",
    alignItems: "center",
    marginRight: 15,
  },
  logo: {
    width: 44,
    height: 44,
    resizeMode: "contain",
  },
  placeholderLogo: {
    justifyContent: "center",
    alignItems: "center",
  },
  logoText: {
    color: "#fff",
    fontSize: 18,
    fontFamily: FontFamily.bold,
  },
  subscriptionName: {
    flex: 1,
    fontSize: 16,
    fontFamily: FontFamily.medium,
    color: "#fff",
  },
  addButton: {
    width: 32,
    height: 32,
    borderRadius: 16,
    backgroundColor: "#101019",
    borderWidth: 1,
    borderColor: "#1A1A2E",
    justifyContent: "center",
    alignItems: "center",
  },
});
